"""Load curated course catalog into `courses` collection.

We deliberately keep this list HAND-CURATED instead of scraping Coursera /
Udemy / freeCodeCamp because:

  1. MongoDB Atlas Vector Search needs only ~30-100 docs to demonstrate the
     hybrid filter + vector ranking story for the hackathon judge video.
  2. Real course catalogs change weekly and most provider APIs require keys
     or aggressive anti-bot bypass.
  3. MongoDB University courses (the ones we want to feature most prominently
     for the "ProductWin" criterion) are stable, free, and have canonical URLs.

The list below intentionally over-weights MongoDB + AI/ML content so that the
gap-analysis demo for a "Backend → AI Engineer" pivot returns rich, relevant
results. Add more entries as needed — the schema is enforced by Zod on read.
"""

from __future__ import annotations

from datetime import datetime, timezone

from _common import get_db, log


# Each course: (title, provider, url, price_usd, hours, level,
#               skills_taught, is_mongodb_official, rating, enrollments, description)
COURSES: list[dict] = [
    # ----- MongoDB University (free, official) -----
    {
        "title": "Introduction to MongoDB",
        "provider": "learn.mongodb.com",
        "url": "https://learn.mongodb.com/learning-paths/introduction-to-mongodb",
        "price_usd": 0,
        "duration_hours": 15,
        "level": "beginner",
        "skills_taught": ["MongoDB", "NoSQL", "Aggregation Pipeline", "MongoDB Atlas"],
        "is_mongodb_official": True,
        "rating": 4.7,
        "enrollment_count": 480_000,
        "description": "Hands-on introduction to MongoDB. Learn CRUD operations, the document model, basic queries, and the aggregation pipeline. Ideal first step before learning advanced features like Atlas Search or Vector Search.",
    },
    {
        "title": "MongoDB Node.js Developer Path",
        "provider": "learn.mongodb.com",
        "url": "https://learn.mongodb.com/learning-paths/mongodb-nodejs-developer-path",
        "price_usd": 0,
        "duration_hours": 20,
        "level": "intermediate",
        "skills_taught": ["MongoDB", "Node.js", "JavaScript", "REST APIs", "Aggregation Pipeline"],
        "is_mongodb_official": True,
        "rating": 4.6,
        "enrollment_count": 220_000,
        "description": "Build modern applications with Node.js using MongoDB as your database. Covers the official Node.js driver, CRUD, indexes, aggregations, transactions, and Atlas Search. Completing the path gets 50% off the Associate Developer (Node.js) certification.",
    },
    {
        "title": "MongoDB Python Developer Path",
        "provider": "learn.mongodb.com",
        "url": "https://learn.mongodb.com/learning-paths/mongodb-python-developer-path",
        "price_usd": 0,
        "duration_hours": 20,
        "level": "intermediate",
        "skills_taught": ["MongoDB", "Python", "PyMongo", "REST APIs", "Aggregation Pipeline"],
        "is_mongodb_official": True,
        "rating": 4.6,
        "enrollment_count": 180_000,
        "description": "Python edition of the developer path. Connect to MongoDB with PyMongo, master CRUD and aggregation pipelines, and prep for the Associate Developer (Python) certification.",
    },
    {
        "title": "MDB200: MongoDB Optimization and Performance",
        "provider": "learn.mongodb.com",
        "url": "https://learn.mongodb.com/courses/mdb200-mongodb-optimization-and-performance",
        "price_usd": 0,
        "duration_hours": 8,
        "level": "advanced",
        "skills_taught": ["MongoDB", "Indexes", "Query Optimization", "explain plans", "Atlas Search", "Vector Search"],
        "is_mongodb_official": True,
        "rating": 4.8,
        "enrollment_count": 95_000,
        "description": "Deep-dive on MongoDB performance. Learn indexing strategies, read explain plans, profile slow operations, and analyze logs and metrics. Includes an intro to Atlas Search and Atlas Vector Search.",
    },
    {
        "title": "MongoDB Data Modeling Path",
        "provider": "learn.mongodb.com",
        "url": "https://learn.mongodb.com/learning-paths/data-modeling-for-mongodb",
        "price_usd": 0,
        "duration_hours": 9,
        "level": "intermediate",
        "skills_taught": ["MongoDB", "Schema Design", "NoSQL", "Indexes"],
        "is_mongodb_official": True,
        "rating": 4.7,
        "enrollment_count": 130_000,
        "description": "Patterns and anti-patterns for designing document schemas in MongoDB. Covers schema design patterns, advanced patterns, anti-patterns, modeling data relationships, and indexing for the Associate Data Modeler certification.",
    },
    {
        "title": "MongoDB Vector Search",
        "provider": "learn.mongodb.com",
        "url": "https://learn.mongodb.com/learning-paths/mongodb-vector-search",
        "price_usd": 0,
        "duration_hours": 6,
        "level": "intermediate",
        "skills_taught": ["MongoDB Atlas", "Vector Databases", "Atlas Search", "Vector Search", "Embeddings", "RAG"],
        "is_mongodb_official": True,
        "rating": 4.9,
        "enrollment_count": 75_000,
        "description": "Build a semantic search and hybrid search pipeline on MongoDB Atlas. Covers $vectorSearch, vector index creation, hybrid lexical+vector queries, RAG, and managing vector search indexes via Atlas CLI and MongoDB Shell.",
    },
    {
        "title": "MongoDB GenAI Developer",
        "provider": "learn.mongodb.com",
        "url": "https://learn.mongodb.com/learning-paths/mongodb-genai-developer",
        "price_usd": 0,
        "duration_hours": 4,
        "level": "advanced",
        "skills_taught": ["MongoDB Atlas", "Vector Databases", "LangChain", "RAG", "LLM API", "Embeddings", "AI Agents"],
        "is_mongodb_official": True,
        "rating": 4.8,
        "enrollment_count": 42_000,
        "description": "End-to-end GenAI track on MongoDB Atlas. Earn skill badges in Vector Search Fundamentals, RAG with MongoDB, and AI Agents with MongoDB. Build a production RAG chatbot and ship LLM-powered features.",
    },
    {
        "title": "Fundamentals of Data Transformation (Aggregation)",
        "provider": "learn.mongodb.com",
        "url": "https://learn.mongodb.com/courses/fundamentals-of-data-transformation",
        "price_usd": 0,
        "duration_hours": 1,
        "level": "intermediate",
        "skills_taught": ["MongoDB", "Aggregation Pipeline", "$lookup", "$match", "$group"],
        "is_mongodb_official": True,
        "rating": 4.7,
        "enrollment_count": 110_000,
        "description": "Skill badge on building aggregation pipelines. Covers $match, $group, $project, $sort, $limit, $lookup, $set, stage ordering, and using explain plans to optimize pipeline performance.",
    },
    # ----- AI / ML / GenAI -----
    {
        "title": "DeepLearning.AI: Generative AI with LLMs",
        "provider": "coursera",
        "url": "https://www.coursera.org/learn/generative-ai-with-llms",
        "price_usd": 49,
        "duration_hours": 16,
        "level": "intermediate",
        "skills_taught": ["LLMs", "Transformers", "Prompt Engineering", "Fine-tuning", "RLHF", "PyTorch"],
        "is_mongodb_official": False,
        "rating": 4.8,
        "enrollment_count": 460_000,
        "description": "Andrew Ng's hands-on tour of how generative LLMs work end-to-end: tokenization, transformer architecture, scaling laws, fine-tuning with LoRA, instruction tuning, and aligning with human feedback (RLHF). Includes labs with Hugging Face and AWS Bedrock.",
    },
    {
        "title": "LangChain for LLM Application Development",
        "provider": "other",
        "url": "https://www.deeplearning.ai/short-courses/langchain-for-llm-application-development/",
        "price_usd": 0,
        "duration_hours": 1,
        "level": "intermediate",
        "skills_taught": ["LangChain", "LLM API", "RAG", "Vector Databases", "Python"],
        "is_mongodb_official": False,
        "rating": 4.6,
        "enrollment_count": 280_000,
        "description": "Free DeepLearning.AI short course taught by Harrison Chase and Andrew Ng. Walks through chains, agents, memory, retrieval, and document QA — the fastest way for a Python backend engineer to ship their first LangChain-powered RAG prototype.",
    },
    {
        "title": "Machine Learning Specialization (Andrew Ng)",
        "provider": "coursera",
        "url": "https://www.coursera.org/specializations/machine-learning-introduction",
        "price_usd": 79,
        "duration_hours": 90,
        "level": "beginner",
        "skills_taught": ["Python", "Scikit-learn", "NumPy", "Pandas", "Machine Learning", "Neural Networks"],
        "is_mongodb_official": False,
        "rating": 4.9,
        "enrollment_count": 720_000,
        "description": "The canonical 3-course intro to ML — supervised learning, advanced learning algorithms, and unsupervised learning. Foundation that every Data Scientist or ML Engineer pivot should pass through.",
    },
    {
        "title": "Practical Deep Learning for Coders (fast.ai)",
        "provider": "other",
        "url": "https://course.fast.ai/",
        "price_usd": 0,
        "duration_hours": 50,
        "level": "intermediate",
        "skills_taught": ["PyTorch", "Deep Learning", "Computer Vision", "NLP", "Python"],
        "is_mongodb_official": False,
        "rating": 4.7,
        "enrollment_count": 350_000,
        "description": "Top-down practical deep learning track. Build real image classifiers, recommender systems, and NLP models on Kaggle datasets — perfect for engineers who already code and want to pivot into ML quickly.",
    },
    {
        "title": "Hugging Face NLP Course",
        "provider": "other",
        "url": "https://huggingface.co/learn/nlp-course",
        "price_usd": 0,
        "duration_hours": 30,
        "level": "intermediate",
        "skills_taught": ["Hugging Face", "Transformers", "PyTorch", "NLP", "Fine-tuning"],
        "is_mongodb_official": False,
        "rating": 4.8,
        "enrollment_count": 220_000,
        "description": "Official Hugging Face track on Transformers and the 🤗 ecosystem. Covers tokenizers, datasets, the trainer API, evaluation, and end-to-end fine-tuning of LLMs and encoder models.",
    },
    {
        "title": "MLOps Specialization (Andrew Ng)",
        "provider": "coursera",
        "url": "https://www.coursera.org/specializations/machine-learning-engineering-for-production-mlops",
        "price_usd": 79,
        "duration_hours": 60,
        "level": "advanced",
        "skills_taught": ["MLflow", "Kubernetes", "Docker", "TensorFlow", "Data Pipelines", "Monitoring"],
        "is_mongodb_official": False,
        "rating": 4.7,
        "enrollment_count": 145_000,
        "description": "Production ML engineering: feature stores, model deployment, monitoring drift, retraining loops, and CI/CD for models. The bridge between Data Scientist and ML Engineer roles.",
    },
    # ----- Backend / Full-stack -----
    {
        "title": "Node.js, Express, MongoDB & More: The Complete Bootcamp",
        "provider": "udemy",
        "url": "https://www.udemy.com/course/nodejs-express-mongodb-bootcamp/",
        "price_usd": 19,
        "duration_hours": 42,
        "level": "intermediate",
        "skills_taught": ["Node.js", "Express.js", "MongoDB", "REST APIs", "JWT"],
        "is_mongodb_official": False,
        "rating": 4.7,
        "enrollment_count": 310_000,
        "description": "Jonas Schmedtmann's project-driven Node + Express + MongoDB course. Build a full booking API with authentication, file uploads, payments, and deployment.",
    },
    {
        "title": "FastAPI: The Complete Course",
        "provider": "udemy",
        "url": "https://www.udemy.com/course/fastapi-the-complete-course/",
        "price_usd": 22,
        "duration_hours": 28,
        "level": "intermediate",
        "skills_taught": ["Python", "FastAPI", "PostgreSQL", "REST APIs", "PyMongo"],
        "is_mongodb_official": False,
        "rating": 4.6,
        "enrollment_count": 120_000,
        "description": "Modern async Python APIs with FastAPI. Pydantic models, JWT auth, SQLAlchemy and PyMongo integration, and OpenAPI-first design. Pairs well with M220P for MongoDB-backed services.",
    },
    {
        "title": "Go: The Complete Developer's Guide (Golang)",
        "provider": "udemy",
        "url": "https://www.udemy.com/course/go-the-complete-developers-guide/",
        "price_usd": 18,
        "duration_hours": 14,
        "level": "intermediate",
        "skills_taught": ["Go", "REST APIs", "Concurrency", "gRPC"],
        "is_mongodb_official": False,
        "rating": 4.6,
        "enrollment_count": 210_000,
        "description": "A focused intro to Go for engineers already familiar with another language. Concurrency primitives, idiomatic project layout, and writing high-throughput HTTP/gRPC services.",
    },
    # ----- Frontend -----
    {
        "title": "The Complete React Developer Course (with Hooks and Redux)",
        "provider": "udemy",
        "url": "https://www.udemy.com/course/react-2nd-edition/",
        "price_usd": 17,
        "duration_hours": 38,
        "level": "intermediate",
        "skills_taught": ["JavaScript", "React", "Redux", "Hooks", "Webpack"],
        "is_mongodb_official": False,
        "rating": 4.6,
        "enrollment_count": 280_000,
        "description": "Project-driven React covering hooks, context, Redux Toolkit, testing with Jest, and deploying to Firebase. Strong base for Frontend → Full-stack pivots.",
    },
    {
        "title": "Next.js 14 & React: The Complete Guide",
        "provider": "udemy",
        "url": "https://www.udemy.com/course/nextjs-react-the-complete-guide/",
        "price_usd": 21,
        "duration_hours": 41,
        "level": "intermediate",
        "skills_taught": ["Next.js", "React", "TypeScript", "Tailwind CSS", "Server Components"],
        "is_mongodb_official": False,
        "rating": 4.7,
        "enrollment_count": 195_000,
        "description": "App router, server components, server actions, streaming, edge runtime, and authentication. Includes a full e-commerce build deployed to Vercel.",
    },
    # ----- DevOps / Cloud -----
    {
        "title": "Docker & Kubernetes: The Practical Guide",
        "provider": "udemy",
        "url": "https://www.udemy.com/course/docker-kubernetes-the-practical-guide/",
        "price_usd": 22,
        "duration_hours": 27,
        "level": "intermediate",
        "skills_taught": ["Docker", "Kubernetes", "Helm", "CI/CD"],
        "is_mongodb_official": False,
        "rating": 4.7,
        "enrollment_count": 240_000,
        "description": "Maximilian Schwarzmüller's project-driven Docker + Kubernetes course. Real microservices deployment to AWS EKS / GCP GKE with Helm and rolling upgrades.",
    },
    {
        "title": "Terraform & AWS: The Complete Guide",
        "provider": "udemy",
        "url": "https://www.udemy.com/course/learn-devops-infrastructure-automation-with-terraform/",
        "price_usd": 19,
        "duration_hours": 18,
        "level": "intermediate",
        "skills_taught": ["Terraform", "AWS", "Infrastructure as Code", "DevOps"],
        "is_mongodb_official": False,
        "rating": 4.5,
        "enrollment_count": 140_000,
        "description": "Provision real AWS infrastructure with Terraform — VPCs, RDS, EKS clusters, IAM. Includes state-management best practices and team workflows.",
    },
    {
        "title": "AWS Certified Solutions Architect Associate (SAA-C03)",
        "provider": "udemy",
        "url": "https://www.udemy.com/course/aws-certified-solutions-architect-associate-saa-c03/",
        "price_usd": 24,
        "duration_hours": 27,
        "level": "intermediate",
        "skills_taught": ["AWS", "Cloud Architecture", "VPC", "S3", "EC2", "DynamoDB"],
        "is_mongodb_official": False,
        "rating": 4.7,
        "enrollment_count": 530_000,
        "description": "Stéphane Maarek's flagship AWS SAA prep. Covers every service in the exam blueprint and the architectural patterns behind them — a strong asset for any Backend → Cloud pivot.",
    },
    # ----- Data / Analytics -----
    {
        "title": "The Complete SQL Bootcamp",
        "provider": "udemy",
        "url": "https://www.udemy.com/course/the-complete-sql-bootcamp/",
        "price_usd": 17,
        "duration_hours": 9,
        "level": "beginner",
        "skills_taught": ["SQL", "PostgreSQL", "Data Analysis"],
        "is_mongodb_official": False,
        "rating": 4.7,
        "enrollment_count": 580_000,
        "description": "Foundational SQL with PostgreSQL — joins, window functions, CTEs, and analytical patterns. Great companion to MongoDB knowledge for engineers working across mixed stacks.",
    },
    {
        "title": "Apache Airflow: The Hands-On Guide",
        "provider": "udemy",
        "url": "https://www.udemy.com/course/the-complete-hands-on-course-to-master-apache-airflow/",
        "price_usd": 19,
        "duration_hours": 12,
        "level": "intermediate",
        "skills_taught": ["Apache Airflow", "Python", "Data Pipelines", "ETL"],
        "is_mongodb_official": False,
        "rating": 4.6,
        "enrollment_count": 90_000,
        "description": "Build production data pipelines with Airflow 2.x. Covers DAG authoring, custom operators, sensors, XComs, the TaskFlow API, and KubernetesExecutor on EKS.",
    },
    {
        "title": "Apache Spark with Python (PySpark)",
        "provider": "udemy",
        "url": "https://www.udemy.com/course/spark-and-python-for-big-data-with-pyspark/",
        "price_usd": 19,
        "duration_hours": 12,
        "level": "intermediate",
        "skills_taught": ["Apache Spark", "Python", "Data Engineering", "Big Data"],
        "is_mongodb_official": False,
        "rating": 4.5,
        "enrollment_count": 175_000,
        "description": "PySpark from zero to Databricks. RDDs, DataFrames, Spark SQL, MLlib, and structured streaming with real datasets.",
    },
    # ----- Mobile -----
    {
        "title": "iOS & Swift: The Complete iOS App Development Bootcamp",
        "provider": "udemy",
        "url": "https://www.udemy.com/course/ios-13-app-development-bootcamp/",
        "price_usd": 22,
        "duration_hours": 60,
        "level": "intermediate",
        "skills_taught": ["Swift", "iOS", "Xcode", "SwiftUI", "Firebase"],
        "is_mongodb_official": False,
        "rating": 4.7,
        "enrollment_count": 380_000,
        "description": "Angela Yu's iOS bootcamp. Builds 20+ apps with Swift and SwiftUI, including Firebase-backed chat and weather apps.",
    },
    {
        "title": "The Complete Android 14 & Kotlin Development Masterclass",
        "provider": "udemy",
        "url": "https://www.udemy.com/course/android-kotlin-developer/",
        "price_usd": 19,
        "duration_hours": 30,
        "level": "intermediate",
        "skills_taught": ["Kotlin", "Android", "Jetpack Compose", "Firebase"],
        "is_mongodb_official": False,
        "rating": 4.5,
        "enrollment_count": 95_000,
        "description": "Modern Android development with Kotlin and Jetpack Compose. MVVM architecture, Room, coroutines, and Firebase backend integration.",
    },
    # ----- Free / Foundational -----
    {
        "title": "freeCodeCamp: Responsive Web Design",
        "provider": "freecodecamp",
        "url": "https://www.freecodecamp.org/learn/responsive-web-design/",
        "price_usd": 0,
        "duration_hours": 300,
        "level": "beginner",
        "skills_taught": ["HTML", "CSS", "Tailwind CSS", "Web Design"],
        "is_mongodb_official": False,
        "rating": 4.8,
        "enrollment_count": 1_200_000,
        "description": "The most accessible free path into web development. ~15 hands-on projects, finishing with a certified portfolio. Solid starting point for career changers entering Frontend roles.",
    },
    {
        "title": "freeCodeCamp: Back End Development and APIs",
        "provider": "freecodecamp",
        "url": "https://www.freecodecamp.org/learn/back-end-development-and-apis/",
        "price_usd": 0,
        "duration_hours": 300,
        "level": "beginner",
        "skills_taught": ["Node.js", "Express.js", "MongoDB", "REST APIs", "Git"],
        "is_mongodb_official": False,
        "rating": 4.7,
        "enrollment_count": 850_000,
        "description": "Free, project-based backend track with Node, Express, and MongoDB. Pairs perfectly with M220JS for a free-only Backend Developer pivot path.",
    },
    {
        "title": "MIT 6.S191: Introduction to Deep Learning",
        "provider": "youtube",
        "url": "https://www.youtube.com/playlist?list=PLtBw6njQRU-rwp5__7C0oIVt26ZgjG9NI",
        "price_usd": 0,
        "duration_hours": 24,
        "level": "intermediate",
        "skills_taught": ["Deep Learning", "PyTorch", "TensorFlow", "Computer Vision", "NLP"],
        "is_mongodb_official": False,
        "rating": 4.8,
        "enrollment_count": 600_000,
        "description": "MIT's flagship deep learning lecture series, free on YouTube. Annual refresh — strong companion to fast.ai for the theoretical foundation.",
    },
]


def main() -> None:
    db = get_db()
    now = datetime.now(timezone.utc)

    docs: list[dict] = []
    for c in COURSES:
        docs.append({**c, "computed_at": now})

    db["courses"].drop()
    res = db["courses"].insert_many(docs)
    log.info("✓ Inserted %d courses", len(res.inserted_ids))

    by_provider: dict[str, int] = {}
    for d in docs:
        by_provider[d["provider"]] = by_provider.get(d["provider"], 0) + 1
    for prov, n in sorted(by_provider.items(), key=lambda kv: -kv[1]):
        log.info("  %-20s %d", prov, n)


if __name__ == "__main__":
    main()
